In [1]:
# importing Numpy and Pandas
import numpy as np
import pandas as pd

In [2]:
# creating inputs
AND = pd.DataFrame({'x1':(0,0,0,0,1,1,1,1),'x2':(0,0,1,1,0,0,1,1),'x3':(0,1,0,1,0,1,0,1),'y':(0,0,0,0,0,0,0,1)})
inputs = AND[['x1','x2','x3']]
inputs

x1  x2  x3
0   0   0   0
1   0   0   1
2   0   1   0
3   0   1   1
4   1   0   0
5   1   0   1
6   1   1   0
7   1   1   1

In [3]:
# creating ouput
output = AND['y']
output

0    0
1    0
2    0
3    0
4    0
5    0
6    0
7    1
Name: y, dtype: int64

In [4]:
# creating weights
weights = np.random.randn(4)*1e-4
weights

array([-9.17599467e-05, -1.69402191e-04, -5.85133079e-05,  5.93266067e-06])

In [5]:
# create activation function
activation_function = lambda inputs,weights:np.where(np.dot(inputs,weights)>0,1,0) 

In [6]:
# creating bias
bias = -np.ones((len(inputs),1))    
bias

array([[-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.]])

In [7]:
# train function
def train(inputs,output,weights,learning_factor,iterations):
    inputs1 = np.c_[inputs,bias]   # stacking bias to input
    for n in range(iterations):
        activation = activation_function(inputs1,weights) #activation function
        print(n,activation)
        weights -= learning_factor*np.dot(np.transpose(inputs1), (activation - output)) # changing weights
        print(n,weights)
    return weights

In [9]:
#final output
w = train(inputs,output,weights,1,20)
w

0 [0 0 0 0 0 0 0 0]
0 [0.99990824 0.9998306  0.99994149 5.00000593]
1 [0 0 0 0 0 0 0 0]
1 [1.99990824 1.9998306  1.99994149 4.00000593]
2 [0 0 0 0 0 0 0 1]
2 [1.99990824 1.9998306  1.99994149 4.00000593]
3 [0 0 0 0 0 0 0 1]
3 [1.99990824 1.9998306  1.99994149 4.00000593]
4 [0 0 0 0 0 0 0 1]
4 [1.99990824 1.9998306  1.99994149 4.00000593]
5 [0 0 0 0 0 0 0 1]
5 [1.99990824 1.9998306  1.99994149 4.00000593]
6 [0 0 0 0 0 0 0 1]
6 [1.99990824 1.9998306  1.99994149 4.00000593]
7 [0 0 0 0 0 0 0 1]
7 [1.99990824 1.9998306  1.99994149 4.00000593]
8 [0 0 0 0 0 0 0 1]
8 [1.99990824 1.9998306  1.99994149 4.00000593]
9 [0 0 0 0 0 0 0 1]
9 [1.99990824 1.9998306  1.99994149 4.00000593]
10 [0 0 0 0 0 0 0 1]
10 [1.99990824 1.9998306  1.99994149 4.00000593]
11 [0 0 0 0 0 0 0 1]
11 [1.99990824 1.9998306  1.99994149 4.00000593]
12 [0 0 0 0 0 0 0 1]
12 [1.99990824 1.9998306  1.99994149 4.00000593]
13 [0 0 0 0 0 0 0 1]
13 [1.99990824 1.9998306  1.99994149 4.00000593]
14 [0 0 0 0 0 0 0 1]
14 [1.99990824 1.99

array([1.99990824, 1.9998306 , 1.99994149, 4.00000593])